import random
post=random.choice(["I don’t care what the question is—the answer is chocolate.",
                    "My moms Its very hard to concentrate when Im in a room full of cookies!",
                    "I just broke my record for most days on earth. High five!",
                    "My goal in life is to have a Wikipedia page written about me. Maybe just a newspaper article. Ok, Id accept a journal entry.",
                    "My bank account balance constantly reassures me that Im safe from identity theft.",
                    "If were not supposed to eat at night, then why is there a light in the fridge?",
                    "Dont you wish they made a clap-on clap-off device for some peoples mouths?",
                    "I get enough exercise pushing my luck.",
                    "My relationship is like a Tesla. I don’t have a Tesla.",
                    "Please cancel my subscription to your issues.",
                    "A clean house is a sign of a wasted life. At least, that’s what I tell myself.",
                    "I have an inferiority complex, but it’s not a very good one.",
                    "¡puɐʇspuɐɥ ɐ ƃuᴉop ǝlᴉɥʍ ʞooqǝɔɐℲ ǝsn oʇ ʍoɥ pǝuɹɐǝl ʎllɐuᴉɟ I",
                    " ██████████ status is loading . . .",
                    "Never interrupt your opponent while he’s making a mistake.",
                    "Sarcasm helps keep people from understanding you’re saying what you really think of them.",
                    "I once prayed to God for a bike but quickly found out He didn’t work that way—so I stole a bike and prayed for His forgiveness.",
                    "A train station is where the train stops. A bus station is where the bus stops. On my desk, I have a workstation…",
                    "You can’t be late until you show up.",
                    "War doesn’t determine who’s right—it determines who’s left.",
                    "If you think things can’t get worse, it’s probably only because you lack sufficient imagination.",
                    "Parents spend the first part of our lives teaching us to walk and talk and the rest of it telling us to sit down and shut up.",
                    "Expecting the world to treat you fairly because you are good is like expecting the bull not to charge because you are a vegetarian.",
                    "Books have the knowledge, knowledge is power, power corrupts, corruption is a crime, and crime doesn’t pay. So if you keep reading, you’ll go broke.",
                    "You can go anywhere you want if you look serious and carry a clipboard.",
                    "I maylooklikeI’m doing nothing, but I’m actively waiting for my problems to go away.",
                    "Every rule has an exception, especially this one.",
                    "History teaches us that men and nations behave wisely once they have exhausted all other alternatives. ~ Abba Eban",
                    "The United States is a nation of laws: badly written and randomly enforced. ~ Frank Zappa",
                    "Don’t let your mind wander—it’s too little to be let out alone.",
                    "Life’s a bitch; if it were easy, it’d be a slut.",
                    "I’d call you a tool, but even they serve a purpose.",
                    "Death is life’s way of telling you that you’ve been fired. Suicide is your way to tell life",
                    "Never argue with idiots. They drag you down to their level, then beat you with experience.",
                    "To err is human. To arr is a pirate.",
                    "I wouldn’t say you’re stupid. You are, but I wouldn’t say it.",
                    "If at first, you don’t succeed, destroy any evidence that you ever tried.",
                    "If at first, you don’t succeed, redefine success.",
                    "If you can’t beat them, arrange to have them beaten.",
                    "Why does life keep teaching me lessons I have no desire to learn?"])
